server:
  port: 8989

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: dev
  ai:
    websearch:
      api-key:  ${kinghy.ai.websearch.api-key}
      searxng:
        url: "http://127.0.0.1:8080/search"
        nums: 10
        engines: "duckduckgo,google,bing,brave,mojeek,presearch,qwant,startpage,yahoo,arxiv,crossref,google_scholar,internetarchivescholar,semantic_scholar"
    dashscope:
      api-key: ${kinghy.dashscope.api-key}

    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimensions: 1536
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/kinghy_rag
    driver-class-name: org.postgresql.Driver

aliyun:
  alioss:
    endpoint: ${kinghy.alioss.endpoint}
    access-key-id: ${kinghy.alioss.access-key-id}
    access-key-secret: ${kinghy.alioss.access-key-secret}
    bucket-name: ${kinghy.alioss.bucket-name}

kinghy:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: kinghy
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: kinghy
    user-ttl: 7200000
    user-token-name: authentication